[build.environment]
    VUE_APP_BSC_NETWORK="56"
    VUE_APP_SERVERLESS="https://api.apwars.farm"
[context.develop.environment]
    VUE_APP_BSC_NETWORK="97"
    VUE_APP_SERVERLESS="https://api-dev.apwars.farm"
[context.deploy-preview.environment]
    VUE_APP_BSC_NETWORK="ALL"
    VUE_APP_SERVERLESS="https://api-dev.apwars.farm"
[[redirects]]
  from = "/battle"
  to = "http://apw-battle.netlify.app"
  status = 200
  force = true